name: Generate snake animation

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - master

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake.svg
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: snake.svg

      - name: Create dist directory
        run: mkdir -p dist

      - name: Move snake.svg to dist
        run: mv snake.svg dist/snake.svg

      - name: List current directory
        run: ls -la

      - name: List dist directory
        run: ls -la dist

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


# name: Generate Datas
# on:
#   schedule: # execute every 12 hours
#     - cron: "* */12 * * *"
#   workflow_dispatch:
# jobs:
#   build:
#     name: Jobs to update datas
#     runs-on: ubuntu-latest
#     steps:
#       # Snake Animation
#       - uses: Platane/snk@master
#         id: snake-gif
  
#         with:
#           github_user_name: Fenil-Patelll
#           svg_out_path: dist/snake.svg
#       - uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
